GET http://localhost:3000/api HTTP/1.1
###
GET https://localhost:3000/api HTTP/1.1
###
GET https://localhost:3000/api/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkhpaUBnbWFpbC5jb20iLCJ1c2VyaWQiOiI2NTQ5Zjg2ODU2YTUyYTEwNDNiODFlNTIiLCJpYXQiOjE2OTkzNDY4NzksImV4cCI6MTY5OTM1NDA3OX0.6fdvk00SkbqGCefdIGQvRKSNLEv_0eZXBEM6u6Gp2-8

###
GET https://localhost:3000/api/posts/{postId} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QzIiwidXNlcmlkIjoiNjUyNmFjYTg5OWRiMzJiNjFhY2M3OTE5IiwiaWF0IjoxNjk5MzQxODUyLCJleHAiOjE2OTkzNDU0NTJ9.wVr-zsljQgyMH7QBfDOCmbGtlpatwTF_myEYujT7C-A

###
POST https://localhost:3000/api/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkhpaUBnbWFpbC5jb20iLCJ1c2VyaWQiOiI2NTQ5Zjg2ODU2YTUyYTEwNDNiODFlNTIiLCJpYXQiOjE2OTkzNDY1OTQsImV4cCI6MTY5OTM1Mzc5NH0.tLmhaBsYMqJ-XhqTCmvje6pkADBdU3dfFAaUeLEhW8A

{
    "title": "Post2",
    "description": "Traffic Department, Pothole in CPT, London rd",
    "departmentCode": "25"
}
###
DELETE https://localhost:3000/api/posts/{postId} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QzIiwidXNlcmlkIjoiNjUyNmFjYTg5OWRiMzJiNjFhY2M3OTE5IiwiaWF0IjoxNjk5MzQxODUyLCJleHAiOjE2OTkzNDU0NTJ9.wVr-zsljQgyMH7QBfDOCmbGtlpatwTF_myEYujT7C-A
###
POST https://localhost:3000/api/users/signup HTTP/1.1
Content-Type: application/json

{
    "username": "test2",
    "email": "Hii@gmail.com",
    "password": "Secrets37"
}
###
POST https://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "Hii@gmail.com",
    "password": "Secrets37"
}
###
//*POST https://localhost:3000/api/posts   {path: 'add', component: CreateComponent}, HTTP/1.1
//Content-Type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QzIiwidXNlcmlkIjoiNjUyNmFjYTg5OWRiMzJiNjFhY2M3OTE5IiwiaWF0IjoxNjk5MzQxODUyLCJleHAiOjE2OTkzNDU0NTJ9.wVr-zsljQgyMH7QBfDOCmbGtlpatwTF_myEYujT7C-A

//{
 //   "title": "Post2",
  //  "description": "Traffic Department, Pothole in CPT, London rd",
//"departmentCode": "25"
//}
###

